#define macros
EXE_NAME = resolvr.exe

.cpp.obj ::
        @echo Compiling...
 cl /c /EHsc /Fo. /I. $<

.c.o ::
        @echo Compiling...
 cl /c /EHsc /Fo. /I. $<

$(EXE_NAME) : resolvr.obj realpath.o
   @echo Linking $(EXE_NAME)...
   link /out:$(DIR_BIN)\$(EXE_NAME) $(DIR_OBJ)\*.obj

resolvr: $(EXE_NAME)


